// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1592177247);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 1437);
user_pref("browser.cache.disk.capacity", 1034240);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1591651668);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{dc672c42-9cf5-4e65-9cc7-840e810aab6c}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1592177227011");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1592179035011");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1592177220321");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1592180820321");
user_pref("browser.search.cohort", "nov17-1");
user_pref("browser.search.region", "AU");
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200429190206");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1591933689");
user_pref("browser.slowStartup.averageTime", 5305);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage", "file:///home/ozi/.local/share/star/star-info.html");
user_pref("browser.startup.homepage_override.buildID", "20200429190206");
user_pref("browser.startup.homepage_override.mstone", "68.8.0");
user_pref("browser.startup.lastColdStartupCheck", 1592177532);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1591651673282");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "68.8.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200429190206");
user_pref("extensions.lastAppVersion", "68.8.0");
user_pref("extensions.lastPlatformVersion", "68.8.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"d8c246dd-c5b1-43f2-a23a-22c4732ffcc9\",\"fxmonitor@mozilla.org\":\"7502ee17-96bb-4afb-a632-465b316691b8\",\"screenshots@mozilla.org\":\"0c5b75b5-0357-4e2c-a70e-ca81519ac98c\",\"webcompat-reporter@mozilla.org\":\"2e8f1e8a-8be1-4a64-a57c-e231690350d8\",\"webcompat@mozilla.org\":\"57bda3f8-da5a-4d96-a31b-ee83a28a862e\",\"default-theme@mozilla.org\":\"f1dba193-ef05-47a6-9bf2-72a481693423\",\"google@search.mozilla.org\":\"1d141daf-2845-4ca8-86c3-4ae053176d11\",\"amazondotcom@search.mozilla.org\":\"7f807653-9fb7-4972-814e-fd01eadc3254\",\"bing@search.mozilla.org\":\"097f0b25-a72f-4ca8-8583-fe8c5af3ef77\",\"ddg@search.mozilla.org\":\"6de3d844-5bcf-4630-9478-f7a0f96e3fa0\",\"ebay@search.mozilla.org\":\"c79a61a1-4be7-4b97-9919-89a4b0eafa2c\",\"twitter@search.mozilla.org\":\"e399729c-e683-4b98-a830-db9f17300c65\",\"wikipedia@search.mozilla.org\":\"aeca02e9-583d-4b17-a809-ec4bfc9420b2\",\"amazon@search.mozilla.org\":\"f501c79a-a993-4e3b-9832-a36a256f4952\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", false);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "270eb0d2-051b-4fc0-961a-6bf149a40b36");
user_pref("security.sandbox.plugin.tempDirSuffix", "95fc227a-0c66-4c62-b8e6-300a0eb7349b");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1592177530);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20200429190206");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
